version: '3.3'

services:

  db:
    image: mysql:8
    container_name: carService_mysql_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carService
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  db_data: